osmo-hlr: Fix /usr/share/osmocom/* not shipped in any package
Since osmo-hlr.git 60673e7f771c3362f9d0d26d4c03cfe85ed5a5b3, a new file
/usr/share/osmocom/osmo-hlr-post-upgrade.sh is installed by "make
install". However, that path is not included in any of the default path
list in FILES_${PN} (see meta/conf/bitbake.conf).

Hence, we must add it manually in order to fix following error:
"""
ERROR: osmo-hlr-1.3.0+gitrAUTOINC+60673e7f77-r2.18.0 do_package: QA Issue: osmo-hlr: Files/directories were installed but not shipped in any package:
  /usr/share/osmocom
  /usr/share/osmocom/osmo-hlr-post-upgrade.sh
Please set FILES such that these items are packaged. Alternatively if they are unneeded, avoid installing them or delete them within do_install.
osmo-hlr: 2 installed and not shipped files. [installed-vs-shipped]
"""

Related: OS#5138
Change-Id: Icdf060f519aaed043eed0dc79779258b0e39006a