libosmo-sccp: Attempt to fix link issue on 201705-nightly builds
This project will build some static libraries needed for testing
and also for downstream users. Do not disable the static build on
newer Poky versions.

arm-poky-linux-gnueabi-libtool: link: arm-poky-linux-gnueabi-gcc -march=armv5te -marm --sysroot=/home/jenkinsdebian8amd64/jenkins/workspace/201705-nightly/label/Debian8-AMD64/build/tmp/work/armv5te-poky-linux-gnueabi/libosmo-sccp/git-r1.18.1/recipe-sysroot -Wall -I/home/jenkinsdebian8amd64/jenkins/workspace/201705-nightly/label/Debian8-AMD64/build/tmp/work/armv5te-poky-linux-gnueabi/libosmo-sccp/git-r1.18.1/recipe-sysroot/usr/include/ -I/home/jenkinsdebian8amd64/jenkins/workspace/201705-nightly/label/Debian8-AMD64/build/tmp/work/armv5te-poky-linux-gnueabi/libosmo-sccp/git-r1.18.1/recipe-sysroot/usr/include/ -O2 -pipe -g -feliminate-unused-debug-types -fdebug-prefix-map=/home/jenkinsdebian8amd64/jenkins/workspace/201705-nightly/label/Debian8-AMD64/build/tmp/work/armv5te-poky-linux-gnueabi/libosmo-sccp/git-r1.18.1=/usr/src/debug/libosmo-sccp/git-r1.18.1 -fdebug-prefix-map=/home/jenkinsdebian8amd64/jenkins/workspace/201705-nightly/label/Debian8-AMD64/build/tmp/work/armv5te-poky-linux-gnueabi/libosmo-sccp/git-r1.18.1/recipe-sysroot-native= -fdebug-prefix-map=/home/jenkinsdebian8amd64/jenkins/workspace/201705-nightly/label/Debian8-AMD64/build/tmp/work/armv5te-poky-linux-gnueabi/libosmo-sccp/git-r1.18.1/recipe-sysroot= -Wl,-O1 -Wl,--hash-style=gnu -Wl,--as-needed -o xua_test xua_test.o sccp_test_data.o  ../../src/.libs/libosmo-sigtran.so -losmogsm -ltalloc -losmovty -losmocore -losmonetif -lsctp
| xua_test.o: In function `test_helpers':
| /usr/src/debug/libosmo-sccp/git-r1.18.1/git/tests/xua/xua_test.c:160: undefined reference to `xua_part_add_gt'
| /usr/src/debug/libosmo-sccp/git-r1.18.1/git/tests/xua/xua_test.c:168: undefined reference to `sua_parse_gt'
| xua_test.o: In function `test_sccp2sua_case':